### ISSUE TITLE
I need some help to understand this package

### ISSUE THREAD

**Issue by devfelipereis** [amsgames/laravel-shop#11]
Hello and thank you for this great package!

I need help :)

I was reading the documentation and I'm not understanding the Item model. 

First, I don't have a model to use as a shoppable item. So, should I use the model Item as a product model? In my case I'm using the model Item as Product(I changed in the config file).
Or, I need to create a new model to be my products model?

And, I didn't understand this attributes:

class — Class reference of the model being used as shoppable item. Optional when using array data.
reference_id — Id reference of the model being used as shoppable item. Optional when using array data.

I'll use them only if I create my own model for products?

Sorry if I'm making some dumb questions but I can't continue without know this.

Thank you!

**Comment by amostajo** [comment]
The magic of this package is that you can convert any existing model and use it as shoppable item thanks to the ShopItemTrait. That is what the properties `class` and `reference_id` are used for.

**Q: I don't have a model to use as a shoppable item. So, should I use the model Item as a product model?**
Yes and No.

Yes, you can use the shop without a shoppable Item, like this:

``` php
$cart->add([
    'sku'    => 'custom.sku',
    'price'  => 9.99
]);
```

But no, you shouldn't user model Item as your product model. The reason why is because the Item model is used to transfer items through carts and orders, and its whole purpose is to keep control of what has been purchased, it should not be used as a product catalog or product database because you'll break its functionality.

**Q: I need to create a new model to be my products model?**
That would be wiser. That way you can manage your products information independently from the checkout system.

OFF TOPIC: One of our future goals is to include a products solution as well, but is out of current development scope.

**Comment by devfelipereis** [comment]
Now I got it. Thank you so much for this fast reply.
