### ISSUE TITLE
Problems with $cart->add(..); in L5.2

### ISSUE THREAD

**Issue by fwartner** [amsgames/laravel-shop#30]
I get `Call to undefined method Illuminate\Database\Query\Builder::add()`when i´m trying to add an item to the cart..

All models are set up properly.

**Comment by ITwrx** [comment]
IIRC, i got that error before when i wasn't logged in to my app with L5.1 as laravel-shop wants to correlate the cart with a user.

**Comment by ghost** [comment]
``` PHP
if(Auth::user()) {
    $shopItem = ShopItem::find(1);
    $cart =Cart::current();
    $cart->add($shopItem);
}
```

**Comment by xyzget** [comment]
`public function user()
    {
        return $this->belongsTo(Config::get('auth.model'), 'user_id');
    }`
laravel 5.2 auth provide a new driver,auth.model was gone!
so you maybe append config key-value to auth.php like this:
`'model' => App\User::class,`

**Comment by paprilia** [comment]
Anyone knows how to solve this issue ?
I got an error 
`Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into`items`(`user_id`,`cart_id`,`sku`,`price`,`tax`,`shipping`,`currency`,`quantity`,`class`,`reference_id`,`updated_at`,`created_at`) values (, 4, website_forum, 8.00, 0, 0, USD, 1, , , 2016-06-08 10:37:13, 2016-06-08 10:37:13))`

despite forcing to add the user_id manually in the add method.

@xyzget  where can I define the `public function user()` ?

**Comment by xyzget** [comment]
@paprilia   

you got an error: `user_id can not be null`.

this package work well with exist user. 

let me show you some source code.

ShopCartTrait line 86:

```
$cartItem = call_user_func( Config::get('shop.item') . '::create', [
                'user_id'       => $this->user->shopId,
                'cart_id'       => $this->attributes['id'],
                'sku'           => is_array($item) ? $item['sku'] : $item->sku,
                'price'         => is_array($item) ? $item['price'] : $item->price,
                'tax'           => is_array($item) 
                                    ? (array_key_exists('tax', $item)
                                        ?   $item['tax']
                                        :   0
                                    ) 
                                    : (isset($item->tax) && !empty($item->tax)
                                        ?   $item->tax
                                        :   0
                                    ),
                'shipping'      => is_array($item) 
                                    ? (array_key_exists('shipping', $item)
                                        ?   $item['shipping']
                                        :   0
                                    ) 
                                    : (isset($item->shipping) && !empty($item->shipping)
                                        ?   $item->shipping
                                        :   0
                                    ),
                'currency'      => Config::get('shop.currency'),
                'quantity'      => $quantity,
                'class'         => is_array($item) ? null : $reflection->getName(),
                'reference_id'  => is_array($item) ? null : $item->shopId,
            ]);
```

and ShopUserTrait line 51:

```
/**
     * Returns the user ID value based on the primary key set for the table.
     *
     * @param mixed
     */
    public function getShopIdAttribute()
    {
        return is_array($this->primaryKey) ? 0 : $this->attributes[$this->primaryKey];
    }
```

when we call $cart->add() function,model will fill user_id attribute with exits User primary key.

so if you want to change the item model attributes fill logic,you must define the add() function in your Item model.

**Comment by paprilia** [comment]
@xyzget Thank you for your reply.

I think the issue lies on the`Cartalyst Sentinel`that I am using. When I try to call the add method, the user is logging in however when I echo `Sentinel::check()`, it always returns false which means that the system or Sentinel does not detect that the user is logging in.

So  I can just overload the add method in the Item model, right?

**Comment by xyzget** [comment]
@paprilia  

`Sentinel` is a package for auth and role-permission service.work with laravel framework,first step we must make sure it is work well with Laravel's Auth system,because Cart::current method will got an user object from Auth::user(),i can't make sure your project is work well with Sentinel package.you maybe get a cart instance for exist user with Cart::findByUser($user_id)

sure,you can change item model's add method,but i suggest don't do that  but you can unserstand everythink.if you change it,you maybe meet other problems,it's a terrible loop,

And i am glad to create a new package to provide servie for laravel 5.2 or later,but i think @amsgames maybe thought laravel 5.1 framework is LTS,so it is not necessary.this package work well with laravel 5.1,

this package work well with some specially usage.if you want do something more with laravel framework,you can send email to zjj@xyzget.com,we can exchanged experience.

**Comment by ghost** [comment]
what does Auth::user() return? you need a user instance in order to assign an item
